# Generated by Django 5.2.15 on 2026-06-27 20:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzeria', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['user', '-created_at'], name='order_user_created_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['status'], name='order_status_idx'),
        ),
        migrations.AddIndex(
            model_name='pizza',
            index=models.Index(fields=['title'], name='pizza_title_idx'),
        ),
        migrations.AddIndex(
            model_name='pizza',
            index=models.Index(fields=['category', 'is_available'], name='pizza_cat_avail_idx'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['pizza', '-created_at'], name='review_pizza_date_idx'),
        ),
    ]
